# Stage 1: Build the Flutter Web app
FROM ghcr.io/cirruslabs/flutter:3.22.1 as build

WORKDIR /app
COPY . .

RUN flutter pub get
RUN flutter build web

# Stage 2: Serve it using NGINX
FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
